### ISSUE TITLE
Cmake Error: cxxoptsConfig.cmake not found

### ISSUE THREAD

**Issue by ParthasarathyBana** [kmedeiros1996/ICP_ROS#1]
Cmake failed with following log:

CMake Error at ICP_ROS/CMakeLists.txt:19 (find_package):
  Could not find a package configuration file provided by "cxxopts" with any
  of the following names:

    cxxoptsConfig.cmake
    cxxopts-config.cmake

  Add the installation prefix of "cxxopts" to CMAKE_PREFIX_PATH or set
  "cxxopts_DIR" to a directory containing one of the above files.  If
  "cxxopts" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!

**Comment by kmedeiros1996** [comment]
Addressed by adding the cxxopts header file directly to the project. See https://github.com/kmedeiros1996/ICP_ROS/commit/4719f4e4e54ad1987aae7f70830e2d1f00b8db84
